'use client'
/*import type { Metadata } from "next";*/
// import { Geist, Geist_Mono } from "next/font/google";
/*import { usePathname } from "next/navigation";*/
import Navbar from "./ui/navBar";

import { Montserrat } from 'next/font/google';
import 'src/app/globals.css'

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Customize weights as needed
  variable: '--font-montserrat' // Optional: add a CSS variable
});

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body

      className={`${montserrat.variable} antialiased`}
      >
        { <Navbar />}
        {children}
      </body>
    </html>
  );
}
